### ISSUE TITLE
Live pages review

### ISSUE THREAD

**Issue by lboeman** [uaenvironment/uaenvironment.github.io#9]
Some issues found on the live rendered https://uaenvironment.github.io/
- The air logo src is missing `?raw=true` to load the image from the repo.
- The overview/projects/publications/students links do not render correctly. The back end Jekyll refuses to render markdown inside an HTML tag. 
- Similarly, the `<summary>` tag sections are causing the markdown inside them to not render.

**Comment by reyg3** [comment]
These have been addressed in #12
